apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: ghcr.io/smithmilner/demo/app:1.0
          env:
            - name: NAME
              value: 'Nik'
            - name: APP_ENV
              value: 'stage'
