apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  tls:
    - hosts:
      - stage.smithmilner.com
      secretName: demo-stage-tls
  rules:
  - host: stage.smithmilner.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demo-svc
            port:
              number: 3000
